#!/usr/bin/env php
<?php

define('AMBER_ROOT_PATH', dirname(dirname(dirname(__DIR__))));

require_once AMBER_ROOT_PATH.'/config/constants.php';
require_once AMBER_ROOT_PATH.'/vendor/autoload.php';

/*
if (defined('AMBER_ROOT_PATH'))
{
  //require_once AMBER_ROOT_PATH.'/amber/framework.php';
}
else
{
  throw new Exception('Unable to load the Amber framework: Path requested - '.AMBER_ROOT_PATH);
}
*/

$args = $argv;
$app = $args[1];
array_splice($args, 1, 1);

echo "Amber Framework: Version 0.x\n";

if ($app)
{
  (new \Amber\System\Resin())->__invoke($app, $args);
}

exit(0);